### GET all EVENTS
GET http://localhost:8080/api/events
Accept: application/json

### GET EVENT by Id
GET http://localhost:8080/api/events/1585dc6d-d59b-4711-8479-c1770bee2f79
Accept: application/json

### ADD an EVENT
POST http://localhost:8080/api/events
Content-Type: application/json

{
  "name": "New Event"
}

### UPDATE an EVENT
PUT http://localhost:8080/api/events/2031f0e0-4b1f-42d6-8550-c2f0d023e323
Content-Type: application/json

{
  "id": "b8cf52dc-f299-4e00-8d98-f5fd075a3759",
  "name": "dsadsda",
  "expenses": [],
  "tags": [],
  "participants": []
}