### ADD an expense to an event
POST http://localhost:8080/api/events/2031f0e0-4b1f-42d6-8550-c2f0d023e323/expenses/
Content-Type: application/json

{
  "title": "abcd",
  "amount": 2.0,
  "date": "2024-03-27T15:16:22.469382",
  "payer": {
    "id": "7bb19bd0-dc9a-4c4e-8de8-be23c47551ec",
    "nickname": "diaco"
  },
  "debtors": [
    {
      "id": "0a170ca4-ca89-43b3-b694-5c483d9e86b0",
      "nickname": "diaco"
    }
  ]
}
### GET all EXPENSES of an EVENT
GET http://localhost:8080/api/events/7235cd83-9f1a-4bdb-9363-7345ea5cf1ad/expenses/
Accept: application/json

### GET EXPENSE by ID
GET http://localhost:8080/api/events/2031f0e0-4b1f-42d6-8550-c2f0d023e323/expenses/6afb91a5-e942-4d62-866a-f584cf342768

### DELETE EXPENSE by ID
DELETE http://localhost:8080/api/events/2031f0e0-4b1f-42d6-8550-c2f0d023e323/expenses/16052803-249b-498e-bef1-10f882fcf160

### ADD an expense to an event
PUT http://localhost:8080/api/events/7235cd83-9f1a-4bdb-9363-7345ea5cf1ad/expenses/fcc9fe83-d2e2-447f-97bd-50bee09ba993
Content-Type: application/json

{
  "id": "fcc9fe83-d2e2-447f-97bd-50bee09ba993",
  "amount": 12.0,
  "title": "abcee",
  "date": "2024-04-04T00:00:00",
  "payer": {
    "id": "4f0466eb-742e-4f23-be9f-208e1015ec20",
    "nickname": "Rares"
  },
  "debtors": [
    {
      "id": "4f0466eb-742e-4f23-be9f-208e1015ec20",
      "nickname": "Rares"
    }
  ]
}