### GET all PARTICIPANTS of an EVENT
GET http://localhost:8080/api/events/d495c08a-6138-4000-882b-3b615dcdd55d/participants/
Accept: application/json

### ADD a PARTICIPANT to an EVENT
POST http://localhost:8080/api/events/d495c08a-6138-4000-882b-3b615dcdd55d/participants/
Content-Type: application/json

{
  "nickname": "ewaen"
}

### UPDATES a PARTICIPANT
PUT http://localhost:8080/api/events/d495c08a-6138-4000-882b-3b615dcdd55d/participants/f0540f8a-6d52-4794-bf70-87ae2950e5bf
Content-Type: application/json

{
  "nickname": "raasdasd22r"
}

### DELETES a participant
DELETE http://localhost:8080/api/events/2031f0e0-4b1f-42d6-8550-c2f0d023e323/participants/07ca37a9-81c2-47e0-a74b-b215eb5a3171